pipelineAccount:
  awsAccountId: 009507777973
  awsRegion: us-west-2

devAccount:
  awsAccountId: 095929019002
  awsRegion: us-west-2

prodAccount:
  awsAccountId: 981445861826
  awsRegion: us-west-2

# Application configuration
applications:
  dev:
    jobs:
      ProcessLegislators:
        inputLocation: "s3://awsglue-datasets/examples/us-legislators/all"
        outputLocation: "s3://glue-data-pipeline-dev-095929019002/output/"
      FileProcessor:
        # Event-driven job - parameters passed by Lambda
        description: "Processes files uploaded to input bucket automatically"
  prod:
    jobs:
      ProcessLegislators:
        inputLocation: "s3://awsglue-datasets/examples/us-legislators/all"
        outputLocation: "s3://glue-data-pipeline-prod-981445861826/output/"
      FileProcessor:
        # Event-driven job - parameters passed by Lambda
        description: "Processes files uploaded to input bucket automatically"
